services:
  - type: web
    name: MedicalRag
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: "10000" 